### ISSUE TITLE
apk plugin broken with Nexus 3.40.0

### ISSUE THREAD

**Issue by NoCoker** [sonatype-nexus-community/nexus-repository-apk#50]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
 After Upgrade to NExus 3.40.0 NExus cannot start up

nexus_1        | 2022-06-30 04:19:47,478+0000 ERROR [quartz-11-thread-1] *SYSTEM org.sonatype.nexus.repository.content.search.SearchFacetImpl - Unable to rebuild search index for repository apk-alpine-3.15-main
nexus_1        | org.sonatype.nexus.repository.MissingFacetException: No facet of type ContentFacet attached to repository apk-alpine-3.15-main
nexus_1        |        at org.sonatype.nexus.repository.manager.internal.RepositoryImpl.facet(RepositoryImpl.java:327)
nexus_1        |        at org.sonatype.nexus.repository.content.search.SearchFacetImpl.rebuildComponentIndex(SearchFacetImpl.java:154)
nexus_1        |        at org.sonatype.nexus.repository.content.search.SearchFacetImpl.rebuildIndex(SearchFacetImpl.java:145)
nexus_1        |        at org.sonatype.nexus.repository.content.search.SearchFacetImpl$$EnhancerByGuice$$430187054.GUICE$TRAMPOLINE(<generated>)
nexus_1        |        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:74)
nexus_1        |        at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
nexus_1        |        at org.sonatype.nexus.common.stateguard.StateGuard$GuardImpl.run(StateGuard.java:272)
nexus_1        |        at org.sonatype.nexus.common.stateguard.GuardedInterceptor.invoke(GuardedInterceptor.java:54)
nexus_1        |        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75)
nexus_1        |        at com.google.inject.internal.InterceptorStackCallback.invoke(InterceptorStackCallback.java:55)
nexus_1        |        at org.sonatype.nexus.repository.content.search.SearchFacetImpl$$EnhancerByGuice$$430187054.rebuildIndex(<generated>)
nexus_1        |        at org.sonatype.nexus.repository.search.index.RebuildIndexTask.execute(RebuildIndexTask.java:33)
nexus_1        |        at org.sonatype.nexus.repository.RepositoryTaskSupport.execute(RepositoryTaskSupport.java:79)
nexus_1        |        at org.sonatype.nexus.scheduling.TaskSupport.call(TaskSupport.java:100)
nexus_1        |        at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.doExecute(QuartzTaskJob.java:143)
nexus_1        |        at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.execute(QuartzTaskJob.java:106)
nexus_1        |        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
nexus_1        |        at org.sonatype.nexus.quartz.internal.QuartzThreadPool.lambda$0(QuartzThreadPool.java:145)
nexus_1        |        at org.sonatype.nexus.thread.internal.MDCAwareRunnable.run(MDCAwareRunnable.java:40)
nexus_1        |        at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
nexus_1        |        at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
nexus_1        |        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
nexus_1        |        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
nexus_1        |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
nexus_1        |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
nexus_1        |        at java.lang.Thread.run(Thread.java:750)

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

cc @DarthHater @bhamail

**Comment by NoCoker** [comment]
Changing the version in pom.xml is also not enough - rebuild not possiable
3.40.1-01 or 3.40.0-03

As i am not a developer i cannot do more - Please have a look :-)

**Comment by NoCoker** [comment]
The Pull Link: https://github.com/sonatype-nexus-community/nexus-repository-apk/pull/51 fix my problems finally !
For me the ticket can be closed - Thanks all :-)
