### ISSUE TITLE
Plugin Compatibility with 3.53.0

### ISSUE THREAD

**Issue by dfeenan29** [sonatype-nexus-community/nexus-repository-apk#55]
Upgraded to latest version (3.53.0) on a Nexus instance with public apk proxy repositories configured and I am receiving an error when trying to start service: "Missing recipe: apk-proxy"

2023-05-03 09:41:14,221-0400 ERROR [FelixStartLevel] EnterpriseSandbox_Primary_1 *SYSTEM org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl - Failed transition: NEW -> STARTED
java.lang.IllegalStateException: Missing recipe: apk-proxy
at com.google.common.base.Preconditions.checkState(Preconditions.java:591)
at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.recipe(RepositoryManagerImpl.java:159)
at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.newRepository(RepositoryManagerImpl.java:177)
at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.restoreRepositories(RepositoryManagerImpl.java:274)
at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.doStart(RepositoryManagerImpl.java:256)
at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:69)
at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:57)
at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:199)
at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:111)
at org.sonatype.nexus.extender.NexusContextListener.moveToPhase(NexusContextListener.java:319)
at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:216)
at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1597)
at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
at java.lang.Thread.run(Thread.java:748)

Bundle.kar file has been moved to /deploy folder but it does not seem to be recognizing it.  Version 3.53.0 contains major fixes for Ruby ahead of the dependency API deprecation so it is a required move.

cc @DarthHater @bhamail

**Comment by Ripolin** [comment]
Hi, it seems installing plugin using kar file is broken in nx 3.53 : https://github.com/sonatype/nexus-public/issues/106

**Comment by NoCoker** [comment]
New Version is released ! https://download.sonatype.com/nexus/3/nexus-3.54.1-01-unix.tar.gz - will test tomorrow and report back here ! but it is commented the bug is fixed !

**Comment by dfeenan29** [comment]
Thanks @NoCoker!  Its odd that your link works but I don't see that new version available on their site (https://help.sonatype.com/repomanager3/product-information/download).  I don't even see 3.54.0 there.

**Comment by marwanbakeer** [comment]
Tested newest v3.54.1 & is actually working fine after the upgrade

**Comment by 805728578** [comment]
v1.0.0
- nexus version: 3.69.0-02
- support apk
- fix download path error
- update nexus dependency version

[v1.0.0 download](https://github.com/805728578/nexus-repository-apk/releases/download/apk-1.0.0/nexus-repository-apk-1.0.0-bundle.kar)
